### ISSUE TITLE
REDCap API Import Records 

### ISSUE THREAD

**Issue by teamocil** [nutterb/redcapAPI#74] opened 2016-10-07 19:46 UTC
Hi, I have been having difficulty trying to import records into REDCap using redcapAPI. I would like to preface by saying I have very limited use and knowledge of R. With that said, I have used the code below:

refToken<-"Token"
test<-read.csv("C:/Users/Desktop/Data.csv")
library(redcapAPI)

rcon <- redcapConnection
(url="https://redcap.nubic.northwestern.edu/redcap/api/" 
token=refToken)

importRecords(rcon, 
              test, 
              overwriteBehavior = "normal",
              returnContent = "ids", 
              returnData = FALSE,
              logfile = "")

The sample data set contains the record ID, and just a few extra fields just to test if the import will go through. The CSV file contains the sample set below. The full data set however has many more variables.

record_id   redcap_event_name   first   last
1   screening_arm_1 First1  Last1
2   screening_arm_1 First2  Last2
3   screening_arm_1 First3  Last3
4   screening_arm_1 First4  Last4
5   screening_arm_1 First5  Last5
6   screening_arm_2 First6  Last6

Every time I try running the code I get the error field:

Error in if (!meta_data$field_name[1] %in% names(data)) { : 
  argument is of length zero

Any help in this would be extremely helpful. Thanks!
- Scott

**Comment by wibeasley** [comment] 2016-10-07 20:02
Hi Scott, let's confirm that the issue is on the R/library side.  Can you first eliminate the possibility that the REDCap project doesn't accepts the CSV, using the 'API Playground'?  If that works, please go through the [trouble-shooting](https://cran.r-project.org/web/packages/REDCapR/vignettes/TroubleshootingApiCalls.html) steps that @nutterb and I helped write.

**Comment by teamocil** [comment] 2016-10-07 20:08
Thank you so much! I should have prefaced before. Using the API playground, I could only manually enter data through a large text box. No where to attach a file. I was confused and someone else had said I could import records through CSV. I have attached the sample R code from the API below.

#!/usr/bin/env Rscript
library(RCurl)
result <- postForm(
    uri='https://redcap.nubic.northwestern.edu/redcap/api/',
    token='token',
    content='record',
    format='csv',
    type='flat',
    overwriteBehavior='normal',
    data='',
    returnContent='count',
    returnFormat='json'
)
print(result)

**Comment by nutterb** [comment] 2016-10-07 21:10
The error message you are receiving seems to suggest either the meta data isn't coming through of there data frame isn't coming through right. Could you share you data dictionary and the names of your `test` data frame?

**Comment by teamocil** [comment] 2016-10-10 17:00
Thank you very much for trying to help me out. I have attached the data dictionary and the test file I want to import below. Thanks.

[EMC2WithIVR_DataDictionary_2016-10-10.xlsx](https://github.com/nutterb/redcapAPI/files/520016/EMC2WithIVR_DataDictionary_2016-10-10.xlsx)
[Data Test 2.xlsx](https://github.com/nutterb/redcapAPI/files/520018/Data.Test.2.xlsx)

**Comment by nutterb** [comment] 2016-10-12 15:08
Just want you to know I haven't forgotten this, but have been on vacation and will need a couple days to catch up on work.

**Comment by teamocil** [comment] 2016-10-18 19:02
Thank you for the update. It's mostly just an issue of if we can automate our process, which if I could get this to work would be ideal.

**Comment by nutterb** [comment] 2016-11-04 11:42
Okay, I have to apologize.  That time I did forget about this.  

But I just put a patch up...it seems `redcapAPI` wasn't correctly converting the meta data to a data frame. 

run `devtools::install_github("nutterb/redcapAPI", ref = "development")` and you'll get the patched version.

**Comment by teamocil** [comment] 2016-11-07 15:43
Thank you very much for updating this. I am however getting an installation error when trying to patch. I have copied the code below. Thanks!


*** arch - i386
c:/Rtools/mingw_32/bin/gcc  -I"C:/Users/sih0948/DOCUME~1/R/R-33~1.1/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"     -O3 -Wall  -std=gnu99 -mtune=core2 -c Rinit.c -o Rinit.o
c:/Rtools/mingw_32/bin/gcc -shared -s -static-libgcc -o redcapAPI.dll tmp.def Rinit.o -Ld:/Compiler/gcc-4.9.3/local330/lib/i386 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/Users/sih0948/DOCUME~1/R/R-33~1.1/bin/i386 -lR
installing to C:/Users/sih0948/Documents/R/R-3.3.1/library/redcapAPI/libs/i386

*** arch - x64
c:/Rtools/mingw_64/bin/gcc  -I"C:/Users/sih0948/DOCUME~1/R/R-33~1.1/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c Rinit.c -o Rinit.o
c:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o redcapAPI.dll tmp.def Rinit.o -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/Users/sih0948/DOCUME~1/R/R-33~1.1/bin/x64 -lR
installing to C:/Users/sih0948/Documents/R/R-3.3.1/library/redcapAPI/libs/x64
** R
** inst
** **preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'htmlTable'
**ERROR: lazy loading failed for package 'redcapAPI'****
* removing 'C:/Users/sih0948/Documents/R/R-3.3.1/library/redcapAPI'
* restoring previous 'C:/Users/sih0948/Documents/R/R-3.3.1/library/redcapAPI'

**Comment by nutterb** [comment] 2016-11-07 18:55
It seems to be having trouble resolving dependencies.  I'd guess R tried to reinstall the `Hmisc` package, and failed.  Make sure you start a fresh R session and run `install.packages(c("Hmisc", "htmlTable"))`  If that runs successfully, try `devtools::install_github("nutterb/redcapAPI", ref = "development")` again.  If that fails again, try `devtools::install_github("nutterb/redcapAPI", ref = "development", dependencies = FALSE)` to skip reinstallation of the dependency packages.

**Comment by teamocil** [comment] 2016-11-11 20:10
Thank you so much for your help in this matter! I have successfully imported a CSV file with multiple records to our REDCap without issue. All your help was greatly appreciated!

**Closed** 2016-11-14 11:47 UTC

**Comment by mattoslmp** [comment] 2019-02-19 20:00
Dear,  I would like to import data (csv) from two instruments (repeated forms) into the same redcap project and I can not put it. I can import the records and data (csv, example bellown) for the instrument 1, but  can't for the instrument2. How Can I import data for two or more instruments. I'm having problem with record ID, because these instrument have distinct records(id)
Bellown the example of redcap instrument 1:

id	fc_paciente	redcap_repeat_instance	redcap_repeat_instrument
1	fc1	1	recepcao
1	fc1.1	2	recepcao
2	fc2	1	recepcao

Thanks for any help you can provide,

Leandro

**Comment by wibeasley** [comment] 2019-02-19 20:05
@mattoslmp, for a few reasons, it probably makes sense to start a new redcapAPI issue for this.  Importing/exporting repeated instruments is has a lot more complexity than a convention import/export.  @nutterb, I and others have been talking about this for a while (for [example](https://github.com/OuhscBbmc/REDCapR/issues/143).  The available calls have recently been expanded too.

@nutterb,  this was news to me last week: https://github.com/aarenson/PHPCap/issues/13

**Comment by nutterb** [comment] 2019-02-19 20:15
@mattoslmp , I believe this is the same as #127 which hasn't gone to CRAN yet.  Please use the proposal there and let me know if that works for you.

**Comment by wibeasley** [comment] 2019-02-19 20:17
@nutterb, I interpreted his question to be about *records*, while #127 is about *files*.

**Comment by nutterb** [comment] 2019-02-19 20:18
Oh.  my mistake.  I'm actually surprised passing a CSV with the `redcap_repeat_instance` doesn't work.

**Comment by mattoslmp** [comment] 2019-02-25 14:28
Hi nutterb, I can import data for one instrument with repeat instance, but can't import when I have two instruments. How can I create a CSV to import data into two instruments with redcapAPI?

**Comment by Abdulazeez2510** [comment] 2022-02-08 16:25
> Thank you so much for your help in this matter! I have successfully imported a CSV file with multiple records to our REDCap without issue. All your help was greatly appreciated!

Hi @teamocil,

Iam trying to import the records through file ino Redcap project using API could you please help me with that?
